on:
  push:
    branches:
      - main
  pull_request:

name: Continuous Integration

defaults:
  run:
    shell: bash

jobs:
  audit:
    name: Cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/audit@v1

  fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt

      - run: cargo fmt --all -- --check

  clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: nightly
            components: clippy

      - run: cargo clippy --all-targets -- -D warnings

  build-and-test-linux:
    name: Build and Test (Linux/stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: stable

      - run: cargo test ./rs_filter --workspace --all-features